### ISSUE TITLE
Notify client if cannot connect to back end

### ISSUE THREAD

**Issue by Li-ReDBox** [eResearchSA/reporting-frontend#24]
We should notify user when http request is time out or any other reasons failed. Infinite looping of spinning wheel is not good. 

We should add error callback to all ng-Resource instances and notify user. The error callback is called with (httpResponse) argument. 

How detail should we report back to user?

**Comment by tomsaleeba** [comment]
I've found https://github.com/Foxandxss/angular-toastr to be easy to work with and it seems to be a modern and stylish way of giving notifications to users.

**Comment by tomsaleeba** [comment]
The commit 966b39d2646e2bb98c677038248de5a0dabb3e86 contains something towards fixing this too. Only realised after I pushed.
