### ISSUE TITLE
Add usage data from HCP to Storage/National

### ISSUE THREAD

**Issue by Li-ReDBox** [eResearchSA/reporting-frontend#25]
Some tenants and namespaces are used by customers whose usage should be included into Storage/National calculation as XFS or HNAS. Here is a list of namespace should be in included in the calculation:

dcp-sa
ersa-fusa-ara-data-0072
ersa-fusa-biosci-fupaleo-93
ersa-fusa-biosci-molecularecologylab-0076
ersa-fusa-clinpharm-mpg-88
ersa-fusa-cnst-nanoscale-0071
ersa-fusa-cnst-nanoscale-71
ersa-fusa-comsc-martelli-101
ersa-fusa-env-mdbfloodmod-90
ersa-fusa-med-fcicembl-80
ersa-fusa-nida-productionarchive-fusa0003
ersa-sagov-dpc-slsa-86
ersa-sahmri-pharma-mindandbrain-91
ersa-uofa-acad-data-uofa0014
ersa-uofa-acpfg-data-9
ersa-uofa-afw-sequencerdata-0073
ersa-uofa-ag-plantdb-plantdb-6
ersa-uofa-ag-plantdb-tpa-backup-6
ersa-uofa-auscover-fractionalcover-2
ersa-uofa-bhis-bhismithdrew-104
ersa-uofa-chemeng-biomolmd-0048
ersa-uofa-chmphy-cssm-uofa0018
ersa-uofa-civen-hydroclimatology-uofa0047
ersa-uofa-coepcw-pcw-seqdata-79
ersa-uofa-coepp-adldata-4
ersa-uofa-coepp-belledata1-74
ersa-uofa-coepp-data-4
ersa-uofa-coepp-meldata-5
ersa-uofa-engage-waiteaboretum-89
ersa-uofa-env-grgbsl-69
ersa-uofa-geol-eeigeophysics-0038
ersa-uofa-lowe-lowelab-0034
ersa-uofa-mbs-proteomics-35
ersa-uofa-mech-medwell-111
ersa-uofa-mobio-womchild-13
ersa-uofa-robinson-ctroberts-10
images
marsuo
pals
water-quality
water-sensitive-urban-design

**Comment by Li-ReDBox** [comment]
HCP api endpoint for usage summary query is:

`/hcp/usage/summary`

It takes arguments of time range as we see in other queries of other endpoints.

Result is an array and each element of it is an object like this:

```javascript
    {
        "bytes_in": 1258697336,
        "bytes_out": 15,
        "deletes": 1,
        "ingested_bytes": 1104771573,
        "metadata_only_bytes": 0,
        "metadata_only_objects": 0,
        "namespace": "images",
        "objects": 911,
        "raw_bytes": 2213543936,
        "reads": 1,
        "tiered_bytes": 0,
        "tiered_objects": 0,
        "writes": 1562
    }
```

`namespace` is mapped to `filesystem` in the ownership object returned from CRM.
`raw_bytes` is the usage in byte which is to be used for calculating cost and displayed as usage.

**Comment by tomsaleeba** [comment]
Service exists now but I still need to add the whitelist function.

**Comment by tomsaleeba** [comment]
Still need to add a popup that shows the currently configured whitelist.

**Comment by tomsaleeba** [comment]
All done and pushed to dev branch.

**Comment by tomsaleeba** [comment]
Reopened because different services need to filter on different fields. At the moment we've only focused on 'filesystem' field.

**Comment by tomsaleeba** [comment]
Done (for real this time) and pushed to dev branch.
