### ISSUE TITLE
admin/storage/allocationSummary has a lot of 'No Value' cells

### ISSUE THREAD

**Issue by tomsaleeba** [eResearchSA/reporting-frontend#40]
Steps:
 - launch the portal as an @ersa.edu.au user
 - go to admin/storage/allocationSummary
 - get any of the reports from Jan - April 2017
 - swap to view the detailed mode

Expected:
Most rows have Allocation Name, School and email filled in.

Actual:
All rows have '(no value)' for those cells.

Notes:
This seems to have happened at the start of this week because I'm fairly sure I wasn't seeing this last week but now I am.

**Comment by tomsaleeba** [comment]
@Li-ReDBox I've got values showing up on the view but I don't know if I've selected the correct fields or if I've fixed the problem in the correct spot. Can you please review?

**Comment by Li-ReDBox** [comment]
I have not changed the fields for this. My run showed most of rows, certainly not "All rows", except some file system name did not match: pals (PALS), marsuo (maruso). Could it because CRM did not return data where you were running it?

**Comment by Li-ReDBox** [comment]
On the same page, I got:

`Data problem: expected field "$$hashKey" values to be equal but were "undefined" and "object:2525"`

The spinner did not stop.

Could this error is caused by no-value rows?

**Comment by tomsaleeba** [comment]
Closing as @Li-ReDBox is happy with my fix.
It would seem that Li tested a version with the fix commit included when he made his first comment and we couldn't reproduce the error from the second comment.
