### ISSUE TITLE
Generate reports targeted at an organisation

### ISSUE THREAD

**Issue by tomsaleeba** [eResearchSA/reporting-frontend#51]
Steps:
 - launch the reportal
 - open a report

Expected:
The user can export the report as a PDF. The export should be complete and ready to send as an invoice. The user will probably need to filter the report down to a single organisation before generating the report; basically do #50 .

Actual:
Generating a report is completely manual. Usually done by download the CSV then manually manipulating a spreadsheet with the data.

**Comment by tomsaleeba** [comment]
Idea 1:
I think the easiest way to generate a report is to make a "print friendly" view of the specified report and let the user "print as PDF". We can just lean on the browsers to do the PDF part, we just have to make something that looks right.

It's easy to achieve with the current tooling, we don't need a server to run code on and we already have to skills to layout web pages.

**Comment by tomsaleeba** [comment]
Idea 2:
We could provision a server that can write PDFs for us. The request to the server can include all the data posted or just some keys and the server can perform the lookup to get the actual data, then it returns a PDF that is downloaded to the user's machine

I'm not a fan of this solution. We would have to also manage a separate server and we need to worry about authoring PDFs. The only benefit of this solution is that the PDF download is triggered for the user but with Firefox, Chrome and Edge all providing print to PDF capability, that's hardly a big selling point.

**Comment by tomsaleeba** [comment]
Idea 3:
It seems there is a pure JS client side solution for generating a PDF: https://github.com/bpampuch/pdfmake. It looks promising and it actively maintained.

**Comment by Li-ReDBox** [comment]
not applicable any more
